// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// messageBox
SEXP messageBox(CharacterVector title, CharacterVector message, CharacterVector diagtype, CharacterVector icontype, IntegerVector value);
RcppExport SEXP _tinyfiledialogs_messageBox(SEXP titleSEXP, SEXP messageSEXP, SEXP diagtypeSEXP, SEXP icontypeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type title(titleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type message(messageSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type diagtype(diagtypeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type icontype(icontypeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(messageBox(title, message, diagtype, icontype, value));
    return rcpp_result_gen;
END_RCPP
}
// inputBox
SEXP inputBox(CharacterVector title, CharacterVector message, SEXP value);
RcppExport SEXP _tinyfiledialogs_inputBox(SEXP titleSEXP, SEXP messageSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type title(titleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type message(messageSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(inputBox(title, message, value));
    return rcpp_result_gen;
END_RCPP
}
// saveFileDialog
SEXP saveFileDialog(CharacterVector title, CharacterVector filepath, IntegerVector nfilters, CharacterVector filters, CharacterVector description);
RcppExport SEXP _tinyfiledialogs_saveFileDialog(SEXP titleSEXP, SEXP filepathSEXP, SEXP nfiltersSEXP, SEXP filtersSEXP, SEXP descriptionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type title(titleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filepath(filepathSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nfilters(nfiltersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filters(filtersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type description(descriptionSEXP);
    rcpp_result_gen = Rcpp::wrap(saveFileDialog(title, filepath, nfilters, filters, description));
    return rcpp_result_gen;
END_RCPP
}
// openFileDialog_
SEXP openFileDialog_(CharacterVector title, CharacterVector filepath, IntegerVector nfilters, CharacterVector filters, CharacterVector description, IntegerVector multiple);
RcppExport SEXP _tinyfiledialogs_openFileDialog_(SEXP titleSEXP, SEXP filepathSEXP, SEXP nfiltersSEXP, SEXP filtersSEXP, SEXP descriptionSEXP, SEXP multipleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type title(titleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filepath(filepathSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nfilters(nfiltersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filters(filtersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type description(descriptionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type multiple(multipleSEXP);
    rcpp_result_gen = Rcpp::wrap(openFileDialog_(title, filepath, nfilters, filters, description, multiple));
    return rcpp_result_gen;
END_RCPP
}
// selectFolderDialog
SEXP selectFolderDialog(CharacterVector title, CharacterVector path);
RcppExport SEXP _tinyfiledialogs_selectFolderDialog(SEXP titleSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type title(titleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(selectFolderDialog(title, path));
    return rcpp_result_gen;
END_RCPP
}
// colorChooser
SEXP colorChooser(CharacterVector title, CharacterVector hexrgb);
RcppExport SEXP _tinyfiledialogs_colorChooser(SEXP titleSEXP, SEXP hexrgbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type title(titleSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type hexrgb(hexrgbSEXP);
    rcpp_result_gen = Rcpp::wrap(colorChooser(title, hexrgb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tinyfiledialogs_messageBox", (DL_FUNC) &_tinyfiledialogs_messageBox, 5},
    {"_tinyfiledialogs_inputBox", (DL_FUNC) &_tinyfiledialogs_inputBox, 3},
    {"_tinyfiledialogs_saveFileDialog", (DL_FUNC) &_tinyfiledialogs_saveFileDialog, 5},
    {"_tinyfiledialogs_openFileDialog_", (DL_FUNC) &_tinyfiledialogs_openFileDialog_, 6},
    {"_tinyfiledialogs_selectFolderDialog", (DL_FUNC) &_tinyfiledialogs_selectFolderDialog, 2},
    {"_tinyfiledialogs_colorChooser", (DL_FUNC) &_tinyfiledialogs_colorChooser, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tinyfiledialogs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
