# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name messageBox
#' @title Display a message
#' @description Show a modal dialog with configurable buttons and icon.
#'
#' @typed title: base::character
#'     \cr Window title
#' @typed message: base::character
#'     \cr A message to display
#' @typed diagtype: base::character
#'     \cr Dialog type (buttons), one of: "ok", "okcancel", "yesno", "yesnocancel"
#' @typed icontype: base::character
#'     \cr Icon displayed on the dialog, one of: "info", "warning", "error", "question"
#' @typed value: base::integer
#'     \cr Default button focus depending on dialog type. 0 for cancel/no, 1 for ok/yes, and 2 for no when diagtype is "yesnocancel"
#'
#'
#' @returns
#' A `character(1)` of the entered string, or NULL if the dialog was cancelled.
NULL

#' @name inputBox
#' @title Input a string
#' @description Get a string from the user and display a message using a system dialog.
#'
#' @typed title: base::character
#'     \cr Window title
#' @typed message: base::character
#'     \cr A message displayed alongside the input
#' @typed value: base::character
#'     \cr The default input string
#'
#'
#' @returns
#' A `character(1)` of the entered string, or NULL if the dialog was cancelled.
NULL

#' @name colorChooser
#' @title Pick a color
#' @description Pick a color using a system dialog.
#'
#' @typed title: base::character
#'     \cr Window title
#' @typed hexrgb: base::character
#'     \cr Pre-selected color
#'
#' @returns
#' A `character(1)` of the selected hex value, or NULL if the dialog was cancelled.
NULL

#' @export
messageBox <- function(title, message, diagtype = "ok", icontype = "info", value = 1L) {
    .Call(`_tinyfiledialogs_messageBox`, title, message, diagtype, icontype, value)
}

#' @export
inputBox <- function(title, message, value) {
    .Call(`_tinyfiledialogs_inputBox`, title, message, value)
}

.saveFileDialog <- function(title, filepath, nfilters, filters, description) {
    .Call(`_tinyfiledialogs_saveFileDialog`, title, filepath, nfilters, filters, description)
}

.openFileDialog <- function(title, filepath, nfilters, filters, description, multiple) {
    .Call(`_tinyfiledialogs_openFileDialog_`, title, filepath, nfilters, filters, description, multiple)
}

.selectFolderDialog <- function(title, path) {
    .Call(`_tinyfiledialogs_selectFolderDialog`, title, path)
}

#' @export
colorChooser <- function(title, hexrgb) {
    .Call(`_tinyfiledialogs_colorChooser`, title, hexrgb)
}

